public class TestAuthorizeDotNetLib {
 /*@isTest
    private static void testclasses(){
   	Account acc = new Account(Name = 'Account');
   	insert acc;
   	Contact con1 = new Contact(FirstName = 'fname', LastName='lname',Type__c= 'Account Administrator',AccountId = acc.Id, User_Name__c = 'TADNL1',Email = 'test@example.com');
   	Contact con2 = new Contact(FirstName = 'fname', LastName='lname',Type__c= 'Account Administrator',AccountId = acc.Id, User_Name__c = 'TADNL2',Email = 'test@example.com');
   	insert con1;
   	insert con2;
   	Location__c loc = new Location__c(Name = 'locName',Account__c = acc.Id, city__c = 'city',Address__c = 'address');
   	insert loc;
   	Assessment__c ass = new Assessment__c();
   	insert ass;
   	Cookie cart = new Cookie('cart','1111,2222,3333,4444,5555,1234,'+ass.Id+','+acc.Id,null,-1,false);
     ApexPages.currentPage().setCookies(new Cookie[]{cart});
   	ApexPages.currentPage().getParameters().put('pid',acc.Id);
        DoPaymentHandler doPayment = new DoPaymentHandler();
        dopayment.totl = 123.12;
        doPayment.process();
        doPayment.getMonths();
        doPayment.getYears();
        doPayment.amount='1234';
        doPayment.firstname='test';
        doPayment.lastname='test';
        doPayment.email='test@test.com';
        doPayment.address='test';
        doPayment.city='test';
        doPayment.state='test';
        doPayment.zip='123456';
        doPayment.cardholder='test';
        doPayment.cardnumber='test';
        doPayment.cardyear='test'; 
        doPayment.cardmonth='test';
        doPayment.cardcvv='test';
        doPayment.expiration='test';
        doPayment.selectedCardType='test';
        doPayment.process();
   }*/
}